project:
  type: book

book:
  title: "**R and Posit tutorials**"
  author: "Section of Epidemiology"
  sidebar: 
    logo: "logo/vetinst-logo.jpg"
    background: "#EEF8F8"
  chapters:
  - index.qmd
  - posit_infrastructure_at_VI.qmd
  - part: "R tutorials"
    chapters: 
      - parallelization_on_workbench.qmd
  - part: "Posit Connect"
    chapters: 
      - Creating_pins_on_Connect.qmd
      - Git_backed_deployment_to_posit_connect.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
